spring.application.name=EMS_backend

server.port=${PORT:8080}

spring.datasource.url=${DB_URL:}
spring.datasource.username=${DB_USERNAME:}
spring.datasource.password=${DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}

jwt.secret=${JWT_SECRET:}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME_LEGACY:}
cloudinary.api-key=${CLOUDINARY_API_KEY_LEGACY:}
cloudinary.api-secret=${CLOUDINARY_API_SECRET_LEGACY:}

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.cache.type=${SPRING_CACHE_TYPE:simple}

#app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS}
